version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
